import type { Metadata } from "next";
import { Montserrat } from "@next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin-ext", "cyrillic-ext"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "TEA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
